FROM openjdk:8
MAINTAINER Rahul <polishettyrahulkumar@gmail.com>
COPY ./zipkin-service-1.0-SNAPSHOT.jar /home/zipkin-service-1.0-SNAPSHOT.jar
CMD ["java", "-jar", "/home/zipkin-service-1.0-SNAPSHOT.jar"]
